### ISSUE TITLE
Unhandle Exception somewhere 

### ISSUE THREAD

**Issue by garrettogrady** [Owen-Miller/IoTSoftwareImplementation#2]
> Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x110695158>
> Traceback (most recent call last):
>   File "/Users/garrettogrady/.pyenv/versions/pyt3/lib/python3.5/site-packages/django/utils/autoreload.py", line 225, in wrapper
>     fn(*args, **kwargs)
>   File "/Users/garrettogrady/.pyenv/versions/pyt3/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
>     self.check(display_num_errors=True)
>   File "/Users/garrettogrady/.pyenv/versions/pyt3/lib/python3.5/site-packages/django/core/management/base.py", line 379, in check
>     include_deployment_checks=include_deployment_checks,
>   File "/Users/garrettogrady/.pyenv/versions/pyt3/lib/python3.5/site-packages/django/core/management/base.py", line 366, in _run_checks
>     return checks.run_checks(**kwargs)
>   File "/Users/garrettogrady/.pyenv/versions/pyt3/lib/python3.5/site-packages/django/core/checks/registry.py", line 71, in run_checks
>     new_errors = check(app_configs=app_configs)
>   File "/Users/garrettogrady/.pyenv/versions/pyt3/lib/python3.5/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
>     all_namespaces = _load_all_namespaces(resolver)
>   File "/Users/garrettogrady/.pyenv/versions/pyt3/lib/python3.5/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
>     url_patterns = getattr(resolver, 'url_patterns', [])
>   File "/Users/garrettogrady/.pyenv/versions/pyt3/lib/python3.5/site-packages/django/utils/functional.py", line 37, in __get__
>     res = instance.__dict__[self.name] = self.func(instance)
>   File "/Users/garrettogrady/.pyenv/versions/pyt3/lib/python3.5/site-packages/django/urls/resolvers.py", line 533, in url_patterns
>     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
>   File "/Users/garrettogrady/.pyenv/versions/pyt3/lib/python3.5/site-packages/django/utils/functional.py", line 37, in __get__
>     res = instance.__dict__[self.name] = self.func(instance)
>   File "/Users/garrettogrady/.pyenv/versions/pyt3/lib/python3.5/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
>     return import_module(self.urlconf_name)
>   File "/Users/garrettogrady/.pyenv/versions/3.5.2/lib/python3.5/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
>   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
>   File "/Users/garrettogrady/Downloads/IoTSoftwareImplementation-master/IoT/urls.py", line 21, in <module>
>     path('gettime/', include('Dashboard.urls'))
>   File "/Users/garrettogrady/.pyenv/versions/pyt3/lib/python3.5/site-packages/django/urls/conf.py", line 34, in include
>     urlconf_module = import_module(urlconf_module)
>   File "/Users/garrettogrady/.pyenv/versions/3.5.2/lib/python3.5/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
>   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
>   File "/Users/garrettogrady/Downloads/IoTSoftwareImplementation-master/Dashboard/urls.py", line 2, in <module>
>     from . import views
>   File "/Users/garrettogrady/Downloads/IoTSoftwareImplementation-master/Dashboard/views.py", line 5, in <module>
>     import matplotlib.pyplot as plt
>   File "/Users/garrettogrady/.pyenv/versions/pyt3/lib/python3.5/site-packages/matplotlib/pyplot.py", line 2374, in <module>
>     switch_backend(rcParams["backend"])
>   File "/Users/garrettogrady/.pyenv/versions/pyt3/lib/python3.5/site-packages/matplotlib/pyplot.py", line 207, in switch_backend
>     backend_mod = importlib.import_module(backend_name)
>   File "/Users/garrettogrady/.pyenv/versions/3.5.2/lib/python3.5/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "/Users/garrettogrady/.pyenv/versions/pyt3/lib/python3.5/site-packages/matplotlib/backends/backend_macosx.py", line 14, in <module>
>     from matplotlib.backends import _macosx
> ImportError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
> 

Not sure what is going on here. did I import something incorrectly?

**Comment by Owen-Miller** [comment]
Check this out
https://stackoverflow.com/questions/21784641/installation-issue-with-matplotlib-python

I think that Mac's  use a different backend than what I used in the code (matplotlib.use('Agg'))

Also, check this out
https://matplotlib.org/tutorials/introductory/usage.html#what-is-a-backend

Thanks, Garrett!
